import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Homepage from '../components/Home'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div className='bg-hero bg-center bg-cover text-white h-screen snap-y snap-mandatory 
    overflow-scroll z-0'>
      <Head>
        <title>Create Next App</title>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <div className='flex'>
      <Homepage/> 
      <section id='hero' className='span-center w-screen'>
      <Hero/>
      </section>
      </div>
      </div>
  )
}

export default Home
